DROP DATABASE database_development;

CREATE DATABASE database_development;

CREATE TABLE `user` (
	`USER_IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(250) NOT NULL,
	`USER_PW` VARCHAR(250) NOT NULL,
	`USER_EMAIL` VARCHAR(250) NOT NULL,
	`USER_NAME` VARCHAR(250) NOT NULL,
	`CREATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`LOGIN_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`USER_IDX`),
	UNIQUE INDEX `USER_ID` (`USER_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `user_visit` (
	`VISIT_IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`VISIT_NUM` INT(11) NOT NULL DEFAULT '0',
	`USER_ID` VARCHAR(250) NOT NULL,
	PRIMARY KEY (`VISIT_IDX`),
	INDEX `USER_ID` (`USER_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `setting` (
	`ST_IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`ST_SOILTYPE` CHAR(50) NULL DEFAULT NULL,
	`ST_WATER` CHAR(50) NULL DEFAULT NULL,
	`ST_SOIL_MOISTURE` CHAR(50) NULL DEFAULT NULL,
	`USER_ID` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`ST_IDX`),
	INDEX `USER_ID` (`USER_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `channel` (
	`CH_IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`CH_NAME` VARCHAR(250) NULL DEFAULT NULL,
	`USER_ID` VARCHAR(250) NULL DEFAULT NULL,
	`CREATE_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`UPDATE_AT` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	`API_KEY` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`CH_IDX`),
	UNIQUE INDEX `API_KEY` (`API_KEY`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `value` (
	`SEN_IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`SEN_TEMPERATURE` INT(11) NOT NULL DEFAULT '0',
	`SEN_HUMIDITY` INT(11) NOT NULL DEFAULT '0',
	`SEN_SOIL_MOISTURE` INT(11) NOT NULL DEFAULT '0',
	`SEN_JSON` VARCHAR(250) NOT NULL,
	`SEN_TOPIC` VARCHAR(250) NOT NULL,
	`SEN_CHANNEL` VARCHAR(250) NOT NULL,
	`USER_ID` VARCHAR(250) NOT NULL,
	`REGISTE_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`API_KEY` VARCHAR(250) NULL DEFAULT NULL,
	PRIMARY KEY (`SEN_IDX`),
	UNIQUE INDEX `API_KEY` (`API_KEY`),
	INDEX `SEN_TOPIC` (`SEN_TOPIC`),
	INDEX `SEN_CHANNEL` (`SEN_CHANNEL`),
	INDEX `USER_ID` (`USER_ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;

CREATE TABLE `topic` (
	`TP_IDX` INT(11) NOT NULL AUTO_INCREMENT,
	`USER_ID` VARCHAR(250) NOT NULL,
	`CH_NAME` VARCHAR(250) NOT NULL,
	`TP_NAME` VARCHAR(250) NOT NULL,
	PRIMARY KEY (`TP_IDX`),
	INDEX `USER_ID` (`USER_ID`),
	INDEX `CH_NAME` (`CH_NAME`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
